# Jocelin Liteanu - Fitting Data

In [11]:
%matplotlib inline
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

from scipy.optimize import curve_fit

# Power on the Moon

<img src="images/ApolloRTG.jpg" alt="Apollo_ALSEP_RTG" style="width: 500px;"/>

The Apollo lunar mission deployed a series of experiments on the Moon, The experiment package
was called the Apollo Lunar Surface Experiments Package (ALSEP). The ALSEP was powered by a radioisotope 
thermoelectric generator (RTG). 

An RTG is basically a fist-sized
slug of Pu-238 wrapped in a material that generates electric power when heated. Since the RTG is powered
by a radioisotope, the output power decreases over time as the radioisotope decays.

## Read in the datafile

The data file `/Data/Apollo_RTG.csv` contains the power output of the Apollo 12 RTG as a function of time.

The data colunms are

* [Day] - Days on the Moon
* [Power] - RTG power output in Watts

In [12]:
my_data1 = pd.read_csv('./Data/Apollo_RTG.csv')
my_data1

Day 
 Power 
 
 
 
 
 0 
 34.4342 
 73.786264 
 
 
 1 
 151.3030 
 73.454312 
 
 
 2 
 297.2840 
 72.385425 
 
 
 3 
 443.4230 
 72.297457 
 
 
 4 
 584.6110 
 71.719237 
 
 
 5 
 740.4550 
 71.385625 
 
 
 6 
 886.5410 
 70.970684 
 
 
 7 
 1042.2800 
 69.983126 
 
 
 8 
 1188.2900 
 69.077725 
 
 
 9 
 1222.2800 
 68.422327 
 
 
 10 
 1280.6800 
 68.011120 
 
 
 11 
 1314.6500 
 67.192235 
 
 
 12 
 1373.0800 
 67.026259 
 
 
 13 
 1436.3200 
 66.451359 
 
 
 14 
 1494.6400 
 65.549693 
 
 
 15 
 1582.1100 
 64.238065 
 
 
 16 
 1645.3100 
 63.417935 
 
 
 17 
 1703.6800 
 62.843242 
 
 
 18 
 1786.3700 
 62.022282 
 
 
 19 
 1878.7600 
 60.955677 
 
 
 20 
 1941.9200 
 59.890317 
 
 
 21 
 2000.2500 
 59.070395 
 
 
 22 
 2019.6800 
 58.742592 
 
 
 23 
 2053.6900 
 58.168936 
 
 
 24 
 2112.0300 
 57.430757 
 
 
 25 
 2136.2600 
 56.612286 
 
 
 26 
 2194.6000 
 55.874107 
 
 
 27 
 2228.5900 
 55.136965 
 
 
 28 
 2262.6500 
 54.890283 
 
 
 29 
 2296.6800 
 54.480114 
 
 
 30 
 2325.8300 
 53.988409 
 
 
 31 
 2345.1600 
 53.006660 
 
 
 32 
 2408.3600 
 52.186530 
 
 
 33 
 2432.6600 
 51.776776 
 
 
 34 
 2461.7800 
 51.121585 
 
 
 35 
 2485.9700 
 50.057884 
 
 
 36 
 2510.2200 
 49.402900 
 
 
 37 
 2573.4500 
 48.746257 
 
 
 38 
 2597.7200 
 48.254760 
 
 
 39 
 2621.8600 
 46.864086 
 
 
 40 
 2655.8400 
 46.126944 
 
 
 41 
 2684.9600 
 45.471753 
 
 
 42 
 3063.3400 
 35.482887 
 
 
 43 
 3320.3200 
 27.951507 
 
 
 44 
 3528.7500 
 21.403122 
 
 
 45 
 3635.4000 
 18.128825

## Can you charge your phone with the Apollo RTG?

* Plot the data: Day vs. Power
* Use the OO interface to matplotlib
* Fit the function with a polynomial (you choose the degree).
* Plot the fit with the data
- Output size w:11in, h:8.5in
- Make the plot look nice (including clear labels)

In [13]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(11,8.5)

fig.tight_layout()

ax.set_xlabel("Day")
ax.set_ylabel("Power")



ax.plot(my_data1['Day'],my_data1['Power'],marker="o",linestyle="None",markersize=10);

In [14]:
my_fit1 = np.polyfit(my_data1['Day'],my_data1['Power'],2)

my_fit1

array([ -4.97341722e-06,   3.42496459e-03,   7.20699442e+01])

In [15]:
my_yfit1 = np.polyval(my_fit1,my_data1['Day'])

In [16]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(11,8.5)

fig.tight_layout()

ax.set_xlabel("Day")
ax.set_ylabel("Power")

ax.plot(my_data1['Day'], my_yfit1, linewidth=5, color='y', linestyle='--');
ax.plot(my_data1['Day'], my_data1['Power'], marker="o", linestyle="None", markersize=10);

## What was the power output on Day 0?

In [17]:
poly01 = np.poly1d(my_fit1)

In [18]:
poly01(0) 

72.06994418130779

## How many years after landing could you still power a 60 W lightbulb?

In [19]:
(poly01 - 60).roots 

array([ 1939.77458322, -1251.12039521])

In [37]:
np.divide((poly01 - 60).roots[0], 365) 

5.3144509129427622

In [21]:
#so about 5.33 years

## How many years after landing could you still power a 5 W USB device?

In [22]:
(poly01 - 5).roots 

array([ 4032.72070124, -3344.06651322])

In [35]:
np.divide((poly01 - 5).roots[0],365)

11.048549866409333

In [24]:
#so about 11 years

## How many years after landing until the power output is 0 W?

In [36]:
np.divide((poly01).roots[0],365) 

11.415278746646008

In [26]:
#so about 11.4 years

---

# Fitting data to a function

* The datafile `./Data/FitMe.csv` contains two columns of data (x,y)
* Use the OO interface to matplotlib
* Plot the data x,y
* Fit the function below to the data
* Find the values of a,b,c that best fit the data
- Output size w:11in, h:8.5in
- Make the plot look nice (including clear labels)

$$\Large f(x) = a \sin(bx) \ e^{-cx} $$

In [27]:
from scipy.optimize import curve_fit

In [28]:
my_data2 = pd.read_csv('./Data/FitMe.csv')

In [29]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(11,8.5)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data2['x'],my_data2['y'],marker="o",linestyle="None",markersize=10);

In [30]:
def function(x,a,b,c):
    return a*np.sin(b*x)*np.exp(-c * x)

In [31]:
my_guess_a = 1.2
my_guess_b = np.pi
my_guess_c = 2

init_guesses = [my_guess_a, my_guess_b, my_guess_c]

In [32]:
fitpars, error = curve_fit(function,my_data2['x'],my_data2['y'],p0=init_guesses)

print(fitpars)

[ 2.53354069  4.11112386  0.34632213]


In [33]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(11,8.5)

fig.tight_layout()

ax.set_xlabel("x")
ax.set_ylabel("y")

ax.plot(my_data2['x'],my_data2['y'],marker="o",linestyle="None",markersize=10);

In [34]:
Z = np.linspace(0,7,100)

fig,ax = plt.subplots(1,1)
fig.set_size_inches(11,8.5)

fig.tight_layout()

ax.set_xlabel("x")
ax.set_ylabel("y")

ax.plot(my_data2['x'],my_data2['y'],marker="o",linestyle="None",markersize=10);

ax.plot(Z, function(Z, *fitpars),      'r-',  linewidth=3)
ax.plot(Z, function(Z, *init_guesses), 'g--', linewidth=3);

### Due Mon Feb 12 - Noon
- `Make sure to change the filename to your name!`
- `Make sure to change the Title to your name!`