# Fitting Data

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## Curve Fitting - Polynomial

In [2]:
my_data1 = pd.read_csv('./Data/fit_data1.csv')
my_data1[0:2]

x 
 y 
 
 
 
 
 0 
 0.4 
 -4.288741 
 
 
 1 
 1.9 
 22.003041

In [3]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data1['x'],my_data1['y'],marker="o",linestyle="None",markersize=10);

## First-order fitting:  $f(x) = ax + b$

In [4]:
my_fit1 = np.polyfit(my_data1['x'],my_data1['y'],1)

my_fit1       # The coefficients of the fit (a,b)

array([9.4650469, 3.8158527])

In [7]:
my_yfit1 = np.polyval(my_fit1,my_data1['x'])   # The polynomial of Fit1 applied to the points my_data1['x']

In [8]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data1['x'], my_yfit1, linewidth=5, color='y', linestyle='--');

ax.plot(my_data1['x'], my_data1['y'], marker="o", linestyle="None", markersize=10);

### You can use `np.poly1d` to explore the fitted polynomial

In [9]:
poly01 = np.poly1d(my_fit1)

In [10]:
poly01(5)                 # value of f(x) at x = 5

51.14108720080091

In [11]:
poly01.roots              # value of x at f(x) = 0

array([-0.40315201])

In [12]:
(poly01 - 20).roots       # value of x at f(x) = 20

array([1.70988559])

## Second-order fitting:  $f(x) = ax^2 + bx + c$

In [13]:
my_data2 = pd.read_csv('./Data/fit_data2.csv')

In [14]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data2['x'],my_data2['y'],marker="o",linestyle="None",markersize=10);

In [15]:
my_fit2 = np.polyfit(my_data2['x'],my_data2['y'],2)

my_fit2

array([-0.87495323, 15.67578454, -2.22790887])

In [16]:
my_yfit2 = np.polyval(my_fit2,my_data2['x'])

In [17]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data2['x'], my_yfit2, linewidth=5, color='y', linestyle='--');
ax.plot(my_data2['x'], my_data2['y'], marker="o", linestyle="None", markersize=10);

### Explore the fitted polynomial

In [18]:
poly02 = np.poly1d(my_fit2)

In [19]:
poly02(5)                 # value of f(x) at x = 5

54.27718300980439

In [20]:
poly02.roots              # value of x at f(x) = 0

array([17.77286999,  0.14326992])

In [21]:
(poly02 - 20).roots       # value of x at f(x) = 20

array([16.36363104,  1.55250886])

In [22]:
(poly02 - 80).roots       # value of x at f(x) = 80, no real root

array([8.95806995+3.7057737j, 8.95806995-3.7057737j])

## Be careful! Very high-order fits may be garbage

In [23]:
my_fit3 = np.polyfit(my_data1['x'],my_data1['y'],10)

xx = np.linspace(0,10,200)

my_yfit3 = np.polyval(my_fit3,xx)

In [24]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.set_ylim(-20,120)

ax.plot(xx, my_yfit3, linewidth=5, color='m', linestyle='-');
ax.plot(my_data1['x'], my_data1['y'], marker="o", linestyle="None", markersize=15);

### Side Topic - The unpack operator (**\***)

 * The unpacking operator takes a list and unpacks each value and sends each, in order.
 * It makes a list **iterable**

In [25]:
my_list = [3.1, 5.6, 11.5, 19.6]

In [26]:
def some_numbers(a, b, c, d):
    my_string = "I have four numbers: {0}, {1}, {2}, and {3}".format(a,b,c,d)
    print(my_string)

##### This will not work as the list (`my_list`) is sent as one blob:

In [27]:
some_numbers(my_list)

TypeError: some_numbers() missing 3 required positional arguments: 'b', 'c', and 'd'

##### This **will** work as the list (`*my_list`) is unpacked and sent as 4 pieces:

In [28]:
some_numbers(*my_list)

I have four numbers: 3.1, 5.6, 11.5, and 19.6


# Fitting a specific function - `scipy.optimize`

In [29]:
from scipy.optimize import curve_fit

In [30]:
my_data3 = pd.read_csv('./Data/fit_data3.csv')

In [31]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data3['x'],my_data3['y'],marker="o",linestyle="None",markersize=10);

$$ \Large f(x) = a \sin(bx) $$

In [32]:
def ringo(x,a,b):
    return a*np.sin(b*x)

##### You need to provide an initial guess to the parameters `a` and `b`

In [33]:
my_guess_a = 75.0
my_guess_b = 1.0/5.0

init_guesses = [my_guess_a, my_guess_b]

In [34]:
fitpars, error = curve_fit(ringo,my_data3['x'],my_data3['y'],p0=init_guesses)

print(fitpars)

[68.14778865  0.1911845 ]


In [35]:
Z = np.linspace(0,100,1000)

fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data3['x'],my_data3['y'],marker="o",linestyle="None",markersize=10);

ax.plot(Z, ringo(Z, *fitpars),      'r-',  linewidth=3)
ax.plot(Z, ringo(Z, *init_guesses), 'g--', linewidth=3);

### Bad initial guesses can lead to very bad fits

In [36]:
my_guess_a = 35.0
my_guess_b = 1.0

init_guesses = [my_guess_a, my_guess_b]

In [37]:
fitpars, error = curve_fit(ringo,my_data3['x'],my_data3['y'],p0=init_guesses)

print(fitpars)

[4.55024387 0.99176996]


In [38]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("This is X")
ax.set_ylabel("This is Y")

ax.plot(my_data3['x'],my_data3['y'],marker="o",linestyle="None",markersize=10);

ax.plot(Z, ringo(Z, *fitpars),      'r-',  linewidth=3)
ax.plot(Z, ringo(Z, *init_guesses), 'g--', linewidth=3);

### An Astronomical Example - Fitting a spectral line

In [39]:
line_data = pd.read_csv('./Data/linedata.csv')

In [40]:
line_data[0:2]

wavelength 
 flux 
 
 
 
 
 0 
 0.0 
 -0.305196 
 
 
 1 
 0.1 
 0.004932

In [41]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("Wavelength")
ax.set_ylabel("Flux")

ax.plot(line_data['wavelength'],line_data['flux'],marker="o",linestyle="None",markersize=8);

#### Fit a gaussian of the form:

$$ \Large f(x) = A e^{-\frac{(x - C)^2}{W}} $$

* A = amplitude of the gaussian
* C = x-value of the central peak of the gaussian
* W = width of the gaussian

In [42]:
def my_gaussian(x, amplitude, center, width):
    return amplitude * np.exp(-(x-center)**2 /width)

In [43]:
amplitude_guess = 5.0
center_guess = 5.0
width_guess = 2.0

init_guesses = [amplitude_guess, center_guess, width_guess]

In [44]:
fitpars, error = curve_fit(my_gaussian,
                           line_data['wavelength'],
                           line_data['flux'],
                           p0=init_guesses)

print(fitpars)

[5.07800577 5.658661   0.97344415]


In [45]:
my_wavelength = np.linspace(0,10,500)

In [46]:
fig,ax = plt.subplots(1,1)
fig.set_size_inches(6,4)

fig.tight_layout()

ax.set_xlabel("Wavelength")
ax.set_ylabel("Flux")

ax.plot(line_data['wavelength'],line_data['flux'],marker="o",linestyle="None",markersize=8);

ax.plot(my_wavelength, my_gaussian(my_wavelength, *fitpars),      'r-',  linewidth=3)
ax.plot(my_wavelength, my_gaussian(my_wavelength, *init_guesses), 'g--', linewidth=3);

### You can explore the fitted functions using `scipy.interpolate`

In [47]:
from scipy.interpolate import UnivariateSpline

In [48]:
my_function = my_gaussian(my_wavelength, *fitpars)

In [49]:
my_fitted_function = UnivariateSpline(my_wavelength, my_function, s=0)

#### Find the flux at wavelength = 6.25

In [50]:
my_fitted_function(6.25)

array(3.54556449)

#### Find the wavelength of the function at flux = half maximum value **(FWHM)**

In [51]:
half_max = my_function.max() / 2.0

half_max

2.5388616624005382

In [52]:
my_flux = half_max

my_moved_function = UnivariateSpline(my_wavelength, (my_function - my_flux), s=0)

my_moved_function.roots()

array([4.83720241, 6.48011959])

In [53]:
fwhm = my_moved_function.roots()[1] - my_moved_function.roots()[0]

fwhm

1.6429171866796608